checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: 'make test'
            coverage:
              file: '.coverage'
              format: 'py-cc'
